import os
import joblib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import shap
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, classification_report, confusion_matrix


def load_processed_data(filepath: str = "data/processed/cleaned_credit_data.csv"):
    """Load cleaned dataset generated by data_pipeline.py."""
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Processed file not found: {filepath}. Run src/data_pipeline.py first.")
    
    df = pd.read_csv(filepath)
    print(f"[MODEL] Loaded processed dataset: {df.shape}")
    return df


def train_credit_model(df: pd.DataFrame, target_col: str = "SeriousDlqin2yrs"):
    """
    Train XGBoost model, calculate Gini/ROC-AUC, and extract SHAP feature importance.
    """
    if target_col not in df.columns:
        raise KeyError(f"Target column '{target_col}' not found in dataframe.")

    X = df.drop(columns=[target_col])
    y = df[target_col]

    # Train / Test split with stratification to maintain default ratio
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.20, random_state=42, stratify=y
    )

    print(f"[MODEL] Training set shape: {X_train.shape}, Test set shape: {X_test.shape}")

    # Train XGBoost model tuned for imbalanced risk data
    model = XGBClassifier(
        n_estimators=120,
        max_depth=4,
        learning_rate=0.05,
        scale_pos_weight=len(y_train[y_train == 0]) / max(1, len(y_train[y_train == 1])),
        random_state=42,
        eval_metric="auc"
    )
    
    model.fit(X_train, y_train)

    # Evaluate Model Metrics
    y_pred_proba = model.predict_proba(X_test)[:, 1]
    roc_auc = roc_auc_score(y_test, y_pred_proba)
    gini = 2 * roc_auc - 1  # Gini = 2 * AUC - 1 (Standard European Banking Metric)

    print("\n--- MODEL PERFORMANCE METRICS ---")
    print(f"ROC-AUC Score:  {roc_auc:.4f}")
    print(f"Gini Coefficient: {gini:.4f}")
    print("---------------------------------\n")

    # Model Risk Management (MRM): Explainability via SHAP
    print("[MRM] Calculating SHAP values for Explainable AI compliance...")
    explainer = shap.TreeExplainer(model)
    shap_values = explainer(X_test)

    # Save model artifacts
    os.makedirs("data/processed", exist_ok=True)
    joblib.dump(model, "data/processed/xgboost_credit_model.joblib")
    print("[MODEL] Saved trained model to data/processed/xgboost_credit_model.joblib")

    metrics = {
        "roc_auc": round(float(roc_auc), 4),
        "gini": round(float(gini), 4),
        "train_samples": int(len(X_train)),
        "test_samples": int(len(X_test)),
        "num_features": int(X.shape[1])
    }

    return model, explainer, shap_values, X_test, y_test, metrics


def run_model_training():
    """Main execution function."""
    df = load_processed_data()
    model, explainer, shap_values, X_test, y_test, metrics = train_credit_model(df)
    return metrics


if __name__ == "__main__":
    run_model_training()